### ISSUE TITLE
3D (more?) support

### ISSUE THREAD

**Issue by yukulele** [pazguille/euclidean#2]
need more than 2 dimensions supports

**Comment by razic** [comment]
@yukulele I wrote the same component with a much more flexible API and support for 2D and 3D.

I'll add support for any dimension sometime this week.

https://github.com/hoverboard/euclidean-distance/

**Comment by pazguille** [comment]
@yukulele cool!
But, you could have forked my project and send to me a pull request with this new features.

Github rules!

**Comment by yukulele** [comment]
I don't simply fork your code because you use named coordinate `{x:5,y:9}` but with array point `[5,9]` you can use something like this:

``` javascript
function distance(a,b){

    if(a.length !== b.length ){
        throw 'Points must be in the same space';
    }
    var square = 0;
    for(var i = 0 ; i < a.length ; i++ ){
        square += a[i] * a[i]  +  b[i] * b[i]; // x*x is faster than Math.pow(x,2);
    }
    return Math.sqrt(square);
}
```

Usage :

``` javascript
dist2D = distance([1,2],[3,-9]);
dist3D = distance([4,3,4],[-1,10,12]);
dist8D = distance([6,1,4,9,12,21,15.6,933.45],[7,9,7,18.5,-53.4,14,-45,99]);
```

**Comment by razic** [comment]
@yukulele my [`euclidean-distance`](http://github.com/hoverboard/euclidean-distance) library now supports calculations in any dimensions with four different ways to call the method:

``` javascript
// 1D
euclideanDistance(x, y);
euclideanDistance([x, y]);
euclideanDistance([x], [y]);
euclideanDistance({ x: x }, { y: y });

// 2D
euclideanDistance(x1, y1, x2, y2);
euclideanDistance([x1, y1, x2, y2]);
euclideanDistance([x1, y1], [x2, y2]);
euclideanDistance({ x: x1, y: y1 }, { x: x2 y: y2 });

// 3D
...
```
